<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chessHour" nsURI="http://www.example.org/chessHour" nsPrefix="chessHour">
  <eClassifiers xsi:type="ecore:EClass" name="Puzzle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" eType="#//Board"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pieceTypes" upperBound="-1"
        eType="#//PieceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pieces" upperBound="-1"
        eType="#//PieceInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PieceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moveRules" upperBound="-1"
        eType="#//MoveRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infinite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moveType" eType="#//MoveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canJumpOverBlocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PieceInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="#//Owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//PieceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="ORTHOGONAL"/>
    <eLiterals name="DIAGONAL" value="1"/>
    <eLiterals name="LSHAPE" value="2"/>
    <eLiterals name="FORWARD" value="3"/>
    <eLiterals name="FORWARD_DIAGONAL" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MoveType">
    <eLiterals name="MOVE_ONLY"/>
    <eLiterals name="CAPTURE_ONLY" value="1"/>
    <eLiterals name="MOVE_OR_CAPTURE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Owner">
    <eLiterals name="PLAYER"/>
    <eLiterals name="OPPONENT" value="1"/>
  </eClassifiers>
</ecore:EPackage>
